package com.slinger;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;

public class CodeGenerator {

    private final Random random = new Random();

    //code for stage 6
    public String generateCodeWithNumbersAndLetters(int length, int possibleSymbols) {

        if (possibleSymbols < 11) {
            return generateCodeWithNumbers(length);
        }

        //need to add letters if length < 11
        List<String> symbols = new ArrayList<>();
        Collections.addAll(symbols, "1", "2", "3", "4", "5", "6", "7", "8", "9", "0");
        Collections.shuffle(symbols);

        //add letters to symbols
        int howMany = possibleSymbols - 10;
        char currentLetter = 'a';

        for (int i = 0; i < howMany; i++) {
            symbols.add(String.valueOf(currentLetter++));
        }

        //shuffle list again to make it more random with letters
        Collections.shuffle(symbols);

        StringBuilder result = new StringBuilder();
        int idx = 0;
        while (idx < length) {
            int randomIdx = random.nextInt(symbols.size() - 1);
            String symbol = symbols.get(randomIdx);

            //check if symbols contains digit or if first digit in result is 0
            if ((result.length() == 0 && symbol.equals("0")) || result.toString().contains(symbol)) {
                continue;
            }

            result.append(symbol);
            idx++;
        }

        return result.toString();
    }


    //code for stage 5
    public String generateCodeWithNumbers(int length) {
        List<Integer> digits = new ArrayList<>();
        int idx = 0;

        while (idx < length) {
            int randomDigit = random.nextInt(10);

            //ignore 0 for first
            if (digits.isEmpty() && randomDigit == 0) continue;

            //ignore repeated digits
            if (digits.contains(randomDigit)) continue;

            digits.add(randomDigit);
            idx++;
        }

        StringBuilder result = new StringBuilder();
        digits.forEach(result::append);
        return result.toString();
    }

    //stage 4
    //code is generated by iterating over the pseudoRandomNumber in reverse order and adding unique digits.
    //at most 10 unique digits can be generated
    public String generateCode(int length) {
        boolean isGenerating = true;
        boolean isGenerated = false;
        long pseudoRandomNumber;
        String strNumber;
        List<Integer> digits = new ArrayList<>();

        while (isGenerating) {
            pseudoRandomNumber = System.nanoTime();
            strNumber = String.valueOf(pseudoRandomNumber);

            for (int i = strNumber.length() - 1; i >= 0; i--) {
                int currentDigit = Character.getNumericValue(strNumber.charAt(i));

                //check if we have seen this digit or if first digit is 0, if so ignore it
                if (digits.contains(currentDigit) || (digits.isEmpty() && currentDigit == 0)) {
                    continue;
                } else {
                    digits.add(currentDigit);
                }

                //check if we have reached desired size
                //and break for loop if we have
                if (digits.size() == length) {
                    isGenerated = true;
                    break;
                }
            }

            if (isGenerated) { //if we have desired length, break loop else go again
                isGenerating = false;
            }
        }

        //have desired digits in list, need to convert to string and return result
        StringBuilder result = new StringBuilder();
        digits.forEach(result::append);
        return result.toString();
    }
}
